config/routes.rb
Rails.application.routes.draw do

  root to: 'homes#top'

  get '/home/about' => 'homes#about'

  devise_for :users

  resources :users, only: [:index, :show, :edit, :update]

  resources :books

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true
  validates :body, length: { maximum: 200}

end

app/models/user.rb
class User < ApplicationRecord

  attachment :profile_image

  has_many :books, dependent: :destroy
#追加
  validates :name, presence: true, length: {minimum:2, maximum: 20}

  validates :introduction, length: { maximum: 50}

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,:recoverable, :rememberable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

   def after_sign_in_path_for(resource)

    user_path(resource.id)

   end



  protected
  def configure_permitted_parameters

    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name,:email, :password, :password_confirmation) }
    devise_parameter_sanitizer.permit(:sign_in) { |u| u.permit(:name, :password, :password_confirmation) }
  end





end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :authenticate_user!

def create
    @user = current_user
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:success] = "You have creatad book successfully."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      render "index"
    end
  end

  def index
    @user = current_user
    @book = Book.new
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
    @user = User.find(@book.user_id)# 本を投稿した人のuser_idを元にuserを探している。
  end


  def edit
    @book = Book.find(params[:id])
    if @book.user_id != current_user.id
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:success] = " successfully"
      redirect_to book_path(@book)
    else
      render "edit"
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    flash[:success] = "Book was successfully destroyed."
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!

  before_action :correct_user, only: [:edit, :update]

  def index
    @user = current_user #サインインしているユーザーを取得する
    @users = User.all
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render "edit"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def correct_user
    @user = User.find(params[:id])
    if current_user != @user
      redirect_to user_path(current_user.id)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="top-message col-md-offset-3 col-md-6" >
      <div class="field_with_errors" style="color: red;">
        <% if @book.errors.any? %>
          <h2><%= @book.errors.count %>errors prohibited this book from being saved:</h2>
          <ul>
            <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>
      </div>

      <h1>Editing Book</h1>
        <%= form_for(@book) do |f| %>
          <div class="row">
            <label>Title</label>
            <%= f.text_field :title, class: "col-xs-12" %>
          </div>
          <div class="row">
            <label>body</label>
            <%= f.text_area :body, class: "col-xs-12" %>
          </div><br>
          <div class="row">
            <p><%= f.submit 'Update Book', class: "btn btn-primary col-xs-12" %></p>
          </div>
        <% end %>
        <div class="link" style="color: #666;">
          <%= link_to "Show", book_path(@book.id), class: "text-muted"%>
          <span> |</span>
          <%= link_to "Back", "/books", class: "text-muted" %>
        </div>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container">
  <div class="row">

    <div class="field_with_errors" style="color: red;">
      <% if @book.errors.any? %>
        <h2><%= @book.errors.count %>errors prohibited this book from being saved:</h2>
        <ul>
          <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
    </div>

    <div class="col-xs-3">
      <h2>User info</h2>
      <%= attachment_image_tag @user, :profile_image, format: 'jpeg', size: "100x100", fallback: "no_image.jpg"  %>
      <table class="table">
        <tr>
          <th>name</th>
          <th><%= @user.name %></th>
        </tr>
        <tr>
          <th>introduction</th>
          <th><%= @user.introduction %></th>
        </tr>
      </table>
      <div class="row">
        <p><%= link_to "", edit_user_path(@user.id), class: "btn btn-default col-xs-12 glyphicon glyphicon-wrench"%></p>
      </div>

      <h2>New book</h2>
        <%= form_for(@book, url: '/books') do |f| %>
        <div class="row">
          <label>Title</label>
           <%= f.text_field :title, class: "col-xs-12" %>
        </div>
        <div class="row">
          <label>Opinion</label>
          <%= f.text_area :body, class: "col-xs-12" %>
        </div><br>
        <div class="row">
          <%= f.submit 'Create Book', class: "btn btn-primary col-xs-12" %>
        </div>
        <% end %>
    </div>

    <div class="col-xs-9">
      <h2>Books</h2>

      <table class="table table-hover">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>
      <% @books.each do |book| %>
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(book.user) do %>
              <%= attachment_image_tag book.user, :profile_image, format: 'jpeg', size: "50x50" %></td>
              <% end %>
            <td><%= link_to book.title, book_path(book) %></td>
            <td><%= book.body %></td>
          </tr>
        </tbody>
      <% end %>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">

    <div class="field_with_errors" style="color: red;">
      <% if @book.errors.any? %>
        <h2><%= @book.errors.count %>errors prohibited this book from being saved:</h2>
        <ul>
          <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
    </div>

    <div class="col-xs-3">
      <h2>User info</h2>
      <%= attachment_image_tag @user, :profile_image, format: 'jpeg', size: "100x100", fallback: "no_image.jpg"  %>
      <table class="table">
        <tr>
          <th>name</th>
          <th><%= @user.name %></th>
        </tr>
        <tr>
          <th>introduction</th>
          <th><%= @user.introduction %></th>
        </tr>
      </table>
      <div class="row">
        <p><%= link_to "", edit_user_path(@user.id), class: "btn btn-default col-xs-12 glyphicon glyphicon-wrench"%></p>
      </div>

      <h2>New book</h2>
        <%= form_for(@book, url: '/books') do |f| %>
        <div class="row">
          <label>Title</label>
           <%= f.text_field :title, class: "col-xs-12" %>
        </div>
        <div class="row">
          <label>Opinion</label>
          <%= f.text_area :body, class: "col-xs-12" %>
        </div><br>
        <div class="row">
          <%= f.submit 'Create Book', class: "btn btn-primary col-xs-12" %>
        </div>
        <% end %>
    </div>

    <div class="col-xs-9">
      <h2>Book detail</h2>
      <table class="table">
        <tr>
          <td><%= attachment_image_tag @book.user, :profile_image, format: 'jpeg', size: "50x50", fallback: "no_image.jpg" %><br>
            <%= link_to @user.name, user_path(@user)%>
          </td>

          <td><%= @book.title %></td>
          <td><%= @book.body %></td>
          <% if current_user.id == @user.id %>
            <div>
            <td><%= link_to "Edit", edit_book_path(@book.id), class: "btn btn-success btn-sm" %></td>
            <td><%= link_to "Destroy", book_path(@book.id), method: :delete, "data-confirm" => "本当に削除しますか?", class: "btn btn-danger btn-sm"%></td>
            </div>
          <% end %>
        </tr>
      </table>
    </div>

  </div>
</div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <h1>welcome to <span class="glyphicon glyphicon-book" aria-hidden="true"></span>Bookers!!</h1>
  </div>
</div>

<div class="col-xs-3 col-xs-offset-9">
  <p>CopyRight Infratop.inc</p>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="top-message col-md-offset-3 col-md-6">
      <h1>welcome to <span class="glyphicon glyphicon-book" aria-hidden="true"></span>Bookers!!</h1>
      <p>In <span class="glyphicon glyphicon-book" aria-hidden="true"></span>Bookers,<br>you can share and exchange your opinions , inpressions , and emotions about various books!</p>
      <div class="btn-rapper">
        <p><%= link_to "log in", new_user_session_path, class: "btn btn-info col-xs-10 col-xs-offset-1" %></p>
        <p><%= link_to "sign up", new_user_registration_path, class: "btn btn-success col-xs-10 col-xs-offset-1" %></p>
      </div>
    </div>
  </div>
</div>

<div class="col-xs-3 col-xs-offset-9">
      <p>CopyRight Infratop.inc</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers3</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
          <div class="navbar-header" style="color: white;" >
            <h4>Bookers</h4>
          </div>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
            <li>
              <%= link_to " Home", user_path(current_user.id), class: "glyphicon glyphicon-home" %>
            </li>
            <li>
              <%= link_to " Users", users_path, class: "glyphicon glyphicon-user" %>
            </li>
            <li>
              <%= link_to " Books", books_path, class: "glyphicon glyphicon-book" %>
            </li>
            <li>
              <%= link_to " logout", destroy_user_session_path, method: :delete, class: "glyphicon glyphicon-log-out" %>
            </li>
            <% else %>
            <li>
              <%= link_to " Home", root_path, class: "glyphicon glyphicon-home" %></li>
            <li>
              <%= link_to " About", '/home/about', class: "glyphicon glyphicon-link" %></li>
            <li>
              <%= link_to " Sign up", new_user_registration_path, class: "glyphicon glyphicon-edit" %>
            </li>
            <li>
              <%= link_to " login", new_user_session_path, class: "glyphicon glyphicon-log-in" %>
            </li>
            <% end %>
          </ul>
        </div>
    </nav>


    <% flash.each do |message_type, message| %>
      <%= message %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">

    <div class="field_with_errors" style="color: red;">
      <% if @user.errors.any? %>
        <h2><%= @user.errors.count %>errors prohibited this book from being saved:</h2>
        <ul>
          <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
    </div>

    <h2>User info</h2>
    <%= form_for(@user, url: user_path) do |f| %>

      <h4>Name</h4>
      <%= f.text_field :name %>

      <h4>Image</h4>
      <%= f.attachment_field :profile_image %>

      <h4>Introducton</h4>
      <%= f.text_area :introduction %>

      <%= f.submit 'Update User' %>

    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">

    <div class="field_with_errors" style="color: red;">
      <% if @book.errors.any? %>
        <h2><%= @book.errors.count %>errors prohibited this book from being saved:</h2>
        <ul>
          <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
    </div>

    <div class="col-xs-3">
      <h2>User info</h2>
      <%= attachment_image_tag @user, :profile_image, format: 'jpeg', size: "100x100", fallback: "no_image.jpg"  %>
      <table class="table">
        <tr>
          <th>name</th>
          <th><%= @user.name %></th>
        </tr>
        <tr>
          <th>introduction</th>
          <th><%= @user.introduction %></th>
        </tr>
      </table>
      <div class="row">
        <p><%= link_to "", edit_user_path(@user.id), class: "btn btn-default col-xs-12 glyphicon glyphicon-wrench"%></p>
      </div>

      <h2>New book</h2>
        <%= form_for(@book, url: '/books') do |f| %>
        <div class="row">
          <label>Title</label>
            <%= f.text_field :title, class: "col-xs-12" %>
        </div>
        <div class="row">
          <label>Opinion</label>
          <%= f.text_area :body, class: "col-xs-12" %>
        </div><br>
        <div class="row">
          <%= f.submit 'Create Book', class: "btn btn-primary col-xs-12" %>
        </div>
        <% end %>
    </div>


    <div class="col-xs-9">
      <h2>Users</h2>
        <table class="table">
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
              <th></th>
            </tr>
          </thead>
        <% @users.each do |user| %>
          <tbody>
            <tr>
              <td><%= attachment_image_tag user, :profile_image, format: 'jpeg', size: "50x50", fallback: "no_image.jpg" %></td>
              <td><%= user.name %></td>
              <td><%= link_to "Show", user_path(user.id) %></td>
            </tr>
          </tbody>
           <% end %>
        </table>
    </div>

  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">

    <div class="field_with_errors" style="color: red;">
      <% if @book.errors.any? %>
        <h2><%= @book.errors.count %>errors prohibited this book from being saved:</h2>
        <ul>
          <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
    </div>

    <div class="col-xs-3">
      <h2>User info</h2>
      <%= attachment_image_tag @user, :profile_image, format: 'jpeg', size: "100x100", fallback: "no_image.jpg"  %>
      <table class="table">
        <tr>
          <th>name</th>
          <th><%= @user.name %></th>
        </tr>
        <tr>
          <th>introduction</th>
          <th><%= @user.introduction %></th>
        </tr>
      </table>
      <div class="row">
        <p><%= link_to "", edit_user_path(@user.id), class: "btn btn-default col-xs-12 glyphicon glyphicon-wrench"%></p>
      </div>

      <h2>New book</h2>
        <%= form_for(@book, url: '/books') do |f| %>
        <div class="row">
          <label>Title</label>
            <%= f.text_field :title, class: "col-xs-12" %>
        </div>
        <div class="row">
          <label>Opinion</label>
          <%= f.text_area :body, class: "col-xs-12" %>
        </div><br>
        <div class="row">
          <%= f.submit 'Create Book', class: "btn btn-primary col-xs-12" %>
        </div>
        <% end %>
    </div>

    <div class="col-xs-9">
      <h2>Books</h2>
      <table class="table table-hover">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>
        <% @user.books.each do |book| %>
        <tbody>
          <tr>
            <td><%= attachment_image_tag @user, :profile_image, format: 'jpeg', size: "50x50", fallback: "no_image.jpg" %></td>
            <td><%= link_to book.title, book_path(book) %></td>
            <td><%= book.body %></td>
          </tr>
        </tbody>
        <% end %>
      </table>
    </div>

  </div>
</div>